---

- name: ------------------------------ CONFUGURATION (all) ------------------------------
  hosts: all
  tasks:

    - name:
      include_tasks: rules/rule_apt_dnf_update.yml

    - name:
      include_tasks: templates/system/template_conf_hostname.yml

    - name:
      include_tasks: templates/system/template_conf_dhclient.yml

- name: ------------------------------ DEPLOY PRODUCTION (mastodon) ------------------------------
  hosts: mastodon
  tasks:

    - name:
      include_tasks: tasks_dependencies/task_system.yml

    - name:
      include_tasks: tasks_dependencies/task_dependencies_installations.yml

    - name:
      include_tasks: tasks_dependencies/task_smtp.yml

    - name:
      include_tasks: tasks_dependencies/task_db.yml

    - name:
      include_tasks: tasks_dependencies/task_mastodon.yml

    - name:
      include_tasks: tasks_dependencies/task_latest.yml

    - name:
      include_tasks: templates/mastodon/template_config_mastodon.yml