---

- name: CONFUGURATION (all)
  hosts: all
  tasks:

    - name: dnf or apt update
      include_tasks: rules/rule_apt_dnf_update.yml

    - name: hostname configuration
      include_tasks: templates/system/template_conf_hostname.yml

    - name: dhclient configuration
      include_tasks: templates/system/template_conf_dhclient.yml

- name: DEPLOY PRODUCTION (mastodon)
  hosts: mastodon
  tasks:

    - name: system configuration
      include_tasks: tasks_dependencies/task_system_mastodon.yml

    - name: db installation
      include_tasks: tasks_dependencies/task_db.yml

    - name: ruby installation
      include_tasks: tasks_dependencies/task_ruby.yml