---

- name: template configuration 
  lineinfile:
    path: /var/www/mastodon/.env.production
    regexp: ^DB_NAME=.*$
    line: "DB_NAME={{ db_name }}"

- name:
  lineinfile:
    path: /var/www/mastodon/.env.production
    regexp: ^DB_PASS=.*$
    line: "DB_PASS={{ postgres_default_password }}"